apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: db
spec:
  redisEnterpriseCluster:
  memorySize: 100MB
  defaultUser: true
  shardCount: 1
  replication: true
  tlsMode: enabled
