apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
spec:
  nodes: 3
  uiServiceType: ClusterIP
  servicesRiggerSpec:
    databaseServiceType: cluster_ip
  redisEnterpriseNodeResources:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  persistentSpec:
    enabled: true
    storageClassName: "standard"
    volumeSize: "10Gi"
